config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  resources :users do
    member do
      post 'follow'
      post 'unfollow'
     end
  end

  resources :posts do
    resources :comments, except: [:index, :new, :show]
  end

  resources :sessions, only: [:new, :create]
  delete '/logout', to: 'sessions#destroy'
  #delete '/post', to: 'posts#destroy'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user#, dependent: :destroy
  belongs_to :post #, dependent: :destroy

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
	validates_uniqueness_of :follower_id, scope: :followed_id
	
end

app/models/user.rb
class User < ActiveRecord::Base
has_many :posts, dependent: :destroy
has_many :comments
has_many :relationships, foreign_key: :follower_id, dependent: :destroy
has_many :followeds, through: :relationships
has_many :reverse_relationships, foreign_key: :followed_id, class_name: "Relationship", dependent: :destroy
has_many :followers, through: :reverse_relationships, source: :follower
validates_presence_of :fname, :lname, :email, :password, :location, :bio

has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>", :small => "25x25>" }, :default_url => "placeholder.png"
validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

	def create
  @user = User.create( user_params )
	end


  def fullname
    fname + " " + lname
  end

private

# Use strong_parameters for attribute whitelisting
# Be sure to update your create() and update() controller methods.

def user_params
  params.require(:user).permit(:avatar)
end
end

app/controllers/anh.rb
# comments controller rb file

class CommentsController < ApplicationController
  before_action :set_comment, only: [:edit, :update, :destroy]

  def create
    @comment = Comment.new
    @comment.body = params[:comment][:body]
    @comment.user_id = current_user.id
    @comment.post_id = params[:post_id]

    if @comment.save
      render partial: 'users/comment', formats: [:html], locals: { comment: @comment }
    end
  end

  # js file

  $(document).ready(function(){

  $('.comment-form form').submit(function(event){
    event.preventDefault();
    params = $(this).serialize();
    url = $(this).attr('action')

    $.post(url, params, function(data) {
      $('.comment-list').append(data);
    });
  });

});

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  

  def current_user
    session[:user_id] ? User.find(session[:user_id]) : nil
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  def create
    @comment = Comment.new
    
    unless params[:comment][:body].empty?
      @comment.body = params[:comment][:body]
      @comment.user_id = current_user.id
      @comment.post_id = params[:post_id]
      @comment.save
    end

    redirect_to users_path
  end

  def edit 
  end 

  def update
    if @comment.update(comment_params)
      flash[:notice] = "Comment updated!"
      redirect_to @post
    else 
      flash[:alert] = "Something went wrong with the update."
      render @post
    end
  end

  def destroy
    if current_user.id == @comment.user.id
    @comment.destroy
    flash[:notice] = "Comment was deleted."
    redirect_to root_path
    else
    flash[:notice] = "You are not the owner of this comment"
    redirect_to root_path
    end  
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  
  def index
    @posts = Post.all
  end

  def show 
  end

  def new 
    @post = Post.new
  end


  def create
    @post = Post.new(post_params)

    unless post_params[:body].empty?
      @post.save
      flash[:notice] = "New post created!"
    else
      flash[:notice] = "Sorry - a post was not made!"
    end

    redirect_to users_url
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "Post updated!"
      redirect_to @post
    else 
      flash[:alert] = "Something went wrong with the update."
      render :edit
    end
  end

  def destroy
      if current_user.id == @post.user.id
      @post.destroy
      flash[:notice] = "Post was deleted."
      redirect_to root_path
    else
      flash[:notice] = "you are not the owner of this post"
      redirect_to root_path
    end  
  end

  private

  def post_params
    params.require(:post).permit(:body).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id])
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.where(email: params[:email]).first
    if @user and @user.password == params[:password]
      session[:user_id] = @user.id
      flash[:notice] = "Logged in!"
      redirect_to users_path
    else
      flash[:alert] = "There was a problem logging you in."
      redirect_to new_session_path
    end
  end  

  def destroy
    @user = (session[:user_id])
    session[:user_id] = nil
    redirect_to root_url

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update, :destroy,:follow,:unfollow]
	  
	def index
		@users = User.all
   	 	@posts = Post.all
		@user = User.new
		@post = Post.new
	end
	
	def show
		@post = Post.new
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id	
			flash[:notice] = "Welcome to our site."
			redirect_to @user
		else
			flash[:alert] = "Hmmm. Something went wrong"
			render :new
		end
	end

	def edit
	end

	def update
		if @user.update(user_params)
			flash[:notice] = "Profile updated"
			redirect_to @user
		else
			flash[:alert] = "There was a problem"
			render :edit
		end
	end

	def destroy
		if @user.destroy
			flash[:notice] = "Account deleted. BYE BYE"
			redirect_to users_path
		else 
			flash[:alert] = "Could not delete. Sorry"
			redirect_to users_path
		end	
	end	


	def follow
		@rel = Relationship.new(follower_id: current_user.id, followed_id: @user.id)
		if @rel.save
			flash[:notice] = "followed!"
			redirect_to @user
		else
		flash[:alert] = "Something went wrong"
		redirect_to @user
		end	
	end
	
	def unfollow
		@rel = Relationship.where(follower_id: current_user.id, followed_id: @user.id).first
		if @rel and @rel.destroy
			flash[:notice] = "unfollowed"
			redirect_to @user
		else
			flash[:alert] = "Something went wrong"
			redirect_to @user
		end
	end	

	private

	def user_params
		params.require(:user).permit(:avatar, :fname, :lname, :email, :password, :location, :bio)
	end	

	def set_user
		@user = User.find(params[:id])
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper

	def current_user
		session[:user_id] ? User.find(session[:user_id]) : nil
	end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_for [@comment, @post], :url => user_post_url(@comment) do |f| %>
	<%= f.string :body %> <br />
	<%= f.submit %>
<%end%>

<%= form_for @comment do |f| %>

  <%= f.label :body %>
  <%= f.text_area :body %> <br />
  <%= f.submit %>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit your comment here!</h1>

<%= render 'form' %>

<%= link_to 'cancel', users_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Raleway&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
  <header>
    <nav>
      <div class="login-link-wrapper">
        <% if current_user %>
            <span><%= link_to "Hello #{current_user.fname}", current_user %> |</span>
            <span><%= link_to "Home", users_path %> |</span>
            <span><%= link_to "Edit", edit_user_path(current_user) %> |</span>
            <span><%= link_to "Sign out", logout_path, method: :delete %></span>
        <%else%>
            <span><%= link_to "Home", root_path %> |</span>

            <span>
              <a id="sign-in" href="#">Sign In</a> |
            </span>

            <span>
              <a id="sign-up" href="#">Create a new account today!</a>
            </span>

        <%end%>
      </div>
    </nav>
  </header>

  <section>
    <div class="shim"></div>
    <%= flash[:notice] if flash[:notice] %>
    <%= flash[:alert] if flash[:alert] %>

    <div class="form-wrapper">
      <%= render 'form' %>
    </div>

    <div class="form-wrapper">
      <%= form_tag('/sessions', method: :post, id: 'sign-in-form') do %>
        <p><%= text_field_tag 'email', nil, placeholder: 'Email', class: "form-control"%></p>
        <p><%= password_field_tag 'password', nil, placeholder: 'Password', class: "form-control" %></p>
        <p><%= submit_tag 'Sign In', class: 'submit-btn' %></p>
      <% end %>
    </div>

    <%= yield %>
  </section>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>

  <%= f.label :body %>
  <%= f.text_area :body %> <br />
  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit your post here!</h1>

<%= render 'form' %>

<%= link_to 'cancel', users_path %>

app/views/posts/index.html.erb
<h1>Post Feed</h1>

<ul>
<% @posts.each do |post| %>

	<li><%= post.body %></li>

 		<% post.comments.each do |comment| %><br/>
      
  		<li>
        <%= comment.body %>
      </li>
      <br/>
  	
  <%end%>

  <%= form_for Comment.new, url: post_comments_path(post.id) do |f| %>
    <%= f.label :body %>
    <%= f.text_field :body %> <br />
    <%= f.submit %>
  <% end %>

<%end%>
</ul>

app/views/posts/new.html.erb
<h1>Create a new post!</h1>

<%= render 'form' %>

<%= link_to 'cancel', users_path %>

app/views/posts/show.html.erb
<h1><%= @post.body %></h1>
<p>posted by <%= @post.user.fname %></p>

app/views/users/_comment.html.erb
<li class="comments">
  <div>
    <span class="comments-name"><%= image_tag comment.user.avatar.url(:small) %> | <%= link_to comment.user.fullname, user_path(comment.user.id) %></span>
    <span class="comments-text"><%= comment.body %></span><br/>
    <span class="time-text">
      <%= comment.created_at.strftime("(commented at %I:%M%p on %m/%d/%Y)") %>
      <% if current_user == comment.user %>
      <%= link_to 'delete', post_comment_path(post, comment), method: :delete,data: {confirm: "Are you sure you want to delete this comment?"}, class: "delete-btn" %>
      <%end%>
    </span>
  </div>
</li>

app/views/users/_form.html.erb
<!-- <div class="form-container"> -->

<%= form_for @user, html: { class: 'sign-up-form' } do |f| %>

  <% if @user.errors.any? %>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <l1><%= message %></l1>
      <%end%>
    </ul>
  <%end%>

  <p><%= f.text_field :fname, class: 'form-control', autofocus: true, placeholder: 'First Name'%></p>
  <p><%= f.text_field :lname, class: 'form-control', autofocus: true, placeholder: 'Last Name' %></p>
  <p><%= f.text_area :bio, class: 'bio-text-area', autofocus: true, placeholder: 'Tell Us About You' %></p>
  <p><%= f.text_field :location, class: 'form-control', autofocus: true, placeholder: 'Location' %></p>
  <p><%= f.text_field :password, class: 'form-control', autofocus: true, placeholder: 'Password' %></p>
  <p><%= f.text_field :email, class: 'form-control', autofocus: true, placeholder: 'Email' %></p>
  <p><%= f.submit 'Join Now', class: 'submit-btn' %></p>

<% end %>

app/views/users/_post.html.erb
<div class="post-container">
  <li class="posts">

    <% if current_user == post.user %>
    <p class="post-delete">
          <%= link_to 'x', post, method: :delete, data: {confirm: "Are you sure you want to delete this post?"} %>
    </p>
    <%end%>


    <span class="post-user-name">
      <%= image_tag post.user.avatar.url(:small) %> |
      <%= link_to post.user.fullname, user_path(post.user.id) %>
    </span>

    <span class="time-text">
      <%= post.created_at.strftime("posted at %I:%M%p on %m/%d/%Y") %>
    </span>

    <p>
      <%= post.body %>
    </p>

    <ul class="comment-list">
      <% post.comments.each do |comment| %>
        <%= render partial: 'comment', locals: { comment: comment, post: post } %>
      <%end%>
    </ul>
    
    <div class="comment-form">
      <%= form_for Comment.new, url: post_comments_path(post.id) do |f| %>
        <div class="comment-form">
          <div><%= f.text_area :body, class: 'form-control', autofocus: true, placeholder: 'Write a comment...' %></div>
          <div class="btn-wrapper"><%= f.submit 'Submit', class: 'submit-btn', cursor: "pointer" %></div>
        </div>
      <% end %>
    </div>
  </li>
</div>

app/views/users/edit.html.erb
<div class="wrapper">
  
  <div class="form-group">
    <p class="edit-title">Edit your profile below!</p>

      <%= form_for @user, :html => { :multipart => true} do |f| %>

      <div>
        <%= image_tag "placeholder.png", class: 'placeholder-img' %>
        <%= f.file_field :avatar, class: 'edit-img-form' %>
      </div>

      <p><%= f.text_field :fname, class: 'edit-form-control', autofocus: true, placeholder: 'First Name'%></p>
      <p><%= f.text_field :lname, class: 'edit-form-control', autofocus: true, placeholder: 'Last Name' %></p>
      <p><%= f.text_area :bio, class: 'edit-text-area', autofocus: true, placeholder: 'Tell Us About You' %></p>
      <p><%=f.text_field :location, class: 'edit-form-control', autofocus: true, placeholder: 'Location' %></p>
      <p><%= f.text_field :email, class: 'edit-form-control', autofocus: true, placeholder: 'Email' %></p>
      <p class="edit-btn-container"><%= f.submit 'Edit Profile', class: 'edit-submit-btn' %></p>

      <p>
        <%= link_to 'Cancel', user_path(@user) %> | 
        <%= link_to 'Back', users_path %>
      </p>

    <%end%>
  </div>
</div>

app/views/users/index.html.erb
<!-- If user is not signed in - landing page for sign in, sign up and about -->
<!-- Else, user's homepage -->
<div class="wrapper">

<!-- user homepage -->
  <% if current_user %>

    <div class="left-column">
      <div class="profile-container">
        <h3><%= "Hello #{current_user.fname}" %></h3>
        <div id="img"><%= image_tag current_user.avatar.url(:thumb) %></div>

        <div class="post-container">
          <%= form_for @post do |f| %>
          <p><%= f.text_area :body, class: 'post-form', autofocus: true, placeholder: 'Make a post...' %></p>
          <p><%= f.submit "Post", class: "submit-btn", cursor: "pointer"%></p>
          <% end %>
        </div>
      </div>

      <h3>All users</h3>
      <ol>
        <% @users.each do |user| %>
          <li>
            <%= image_tag user.avatar.url(:small) %> |
            <%= link_to user.fname, user %> |
            <%= user.location %>
          </li>
        <% end %>
      </ol>
    </div>


    <div class="right-column">
      <h3>Friend's Posts</h3>
      <div class="post-feed">
        <ul>
          <% @posts.each do |post| %>
          <%= render partial: 'post', locals: { post: post } %>
            <%end%>
        </ul>
      </div>
    </div>


  <%else%>
    <!-- if not logged in. -->
    <div class="title">
      <h3>Been There?</h3>
      <p>A place to blog about about your favorite places to eat in the city!</p>
    </div>
  <%end%>
</div>

app/views/users/new.html.erb
<h1>Create a new account below!</h1>

<%= render 'form' %>

<p><%= link_to "cancel", users_path(@user) %></p>

app/views/users/show.html.erb
<!-- user's profile page -->
<div class="wrapper">

  <div class="left-column">
    <div class="profile-container">
      <h3><%= @user.fname %>'s Profile Page</h3>
      <div id="img"><%= image_tag @user.avatar.url(:thumb) %></div>
      <p><h3>Location:</h3> <%= @user.location %></p>
      <div><h3>Bio:</h3> <%= @user.bio %> <br><br><%= button_to 'Edit Profile', edit_user_path, method: :get %></div>
    </div>

    <div class="post-container">
      <%= form_for @post do |f| %>
        <p><%= f.text_area :body, class: 'post-form', autofocus: true, placeholder: 'Make a post...' %></p>
        <p><%= f.submit "Post", class: "submit-btn", cursor: "pointer"%></p>
      <% end %>
    </div>


    <h3><%= @user.followeds.empty? ? "#{@user.fname} is not following anyone." : "Following"%></h3>

    <ul>
      <% @user.followeds.each do |user| %>
      <li><%= link_to user.fname, user%></li>
      <%end%>
    </ul>
    
    <% if current_user and @user != current_user %>
      <% if current_user.followeds.include? @user %>
        <%= link_to 'unfollow', unfollow_user_path(@user), method: :post %>
      <% else %>
        <%= link_to 'follow', follow_user_path(@user), method: :post %>
      <% end %>
    <% end %>
  </div>



 <div class="right-column">
    <h3><%= @user.fname %>'s Posts</h3>
    <% @user.posts.each do |post| %>
      <div class="posts post-container">

        <div class="post-delete">
        <% if current_user == @post.user %>
          <%= link_to 'x', post, method: :delete, remote: true, class: "delete-user", data: {confirm: "Are you sure you want to delete this post?"} %>
          <%end%>
        </div>

        <div>
          <%= post.body %>
        </div>

        <div class="time-text">
          <%= post.created_at.strftime("#{@user.fname} posted at %I:%M%p on %m/%d/%Y") %>
        </div>
      </div>

    <%end%>
  </div>

 
</div>
<!-- 
<p>
<%= link_to 'edit user', edit_user_path(@user) %> | 
<%= link_to 'back to users', users_path %>
</p> -->